# Generated by Django 3.0.7 on 2021-02-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_simple_gallery', '0004_auto_20210218_1022'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('simplegalleryindex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtail_simple_gallery.SimpleGalleryIndex')),
                ('date', models.DateField(blank=True, verbose_name='Event Date')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtail_simple_gallery.simplegalleryindex',),
        ),
    ]
