# Generated by Django 3.0.7 on 2021-02-21 06:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtail_simple_gallery', '0004_auto_20210218_1022'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0002_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryIndex',
        ),
    ]
