# Generated by Django 3.0.7 on 2021-02-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('gallery', '0002_simplegalleryindexextend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleGalleryIndexExtend',
        ),
    ]
