# Generated by Django 3.0.7 on 2021-02-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210221_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryindex',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
