# Generated by Django 3.0.7 on 2021-02-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('gallery', '0004_galleryindex_youtube_video_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryIndex',
        ),
    ]
