# Generated by Django 3.0.7 on 2021-02-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_delete_galleryindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='content',
        ),
    ]
