# Generated by Django 3.0.7 on 2021-02-07 16:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('contact', '0007_auto_20210207_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='banner_overlay',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Select color of banner overlay', max_length=7, null=True, verbose_name='Banner Overlay Color'),
        ),
    ]
