# Generated by Django 3.0.7 on 2020-06-28 23:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blog', '0005_delete_postpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='banner_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
