# Generated by Django 3.0.7 on 2021-02-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blog', '0007_auto_20200629_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='banner_subtitle',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
