# Generated by Django 3.0.7 on 2021-02-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(help_text='Your Facebook page URL')),
                ('instagram', models.URLField(help_text='Your Instagram acount URL')),
                ('twitter', models.URLField(help_text='Your Twitter page URL')),
                ('pinterest', models.URLField(help_text='Your pinterest page URL')),
                ('youtube', models.URLField(help_text='Your YouTube channel or user account URL')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Office Hours')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Office Hours')),
                ('donate', models.CharField(blank=True, max_length=20, null=True)),
                ('donate_url', models.URLField(blank=True)),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
