# Generated by Django 3.0.7 on 2021-02-05 13:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basesettings',
            name='donate',
        ),
        migrations.RemoveField(
            model_name='basesettings',
            name='donate_url',
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL'),
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Your Instagram acount URL'),
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='pinterest',
            field=models.URLField(blank=True, help_text='Your pinterest page URL'),
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Your Twitter page URL'),
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube channel or user account URL'),
        ),
        migrations.CreateModel(
            name='SiteTabLinkButtons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('button_text', models.CharField(max_length=20, null=True)),
                ('button_url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_buttons', to='settings.BaseSettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
