# Generated by Django 3.0.7 on 2021-02-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20210205_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesettings',
            name='short_address',
            field=models.CharField(blank=True, help_text='A short and limited version of address', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='basesettings',
            name='address',
            field=models.CharField(blank=True, help_text='A longer more detailed verson of address', max_length=255, null=True),
        ),
    ]
