# Generated by Django 3.0.7 on 2021-02-06 21:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210205_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesettings',
            name='address',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A longer more detailed verson of address', null=True),
        ),
    ]
