# Generated by Django 3.0.7 on 2021-02-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20210206_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesettings',
            name='address',
            field=models.CharField(blank=True, help_text='A longer more detailed verson of address', max_length=255, null=True),
        ),
    ]
