# Generated by Django 3.0.7 on 2021-02-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210206_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='carousel',
        ),
    ]
