# Generated by Django 3.0.7 on 2021-02-06 11:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210206_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='c',
            field=wagtail.core.fields.StreamField([('carousel_items', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(label='Nadpis', max_length=128)), ('text', wagtail.core.blocks.CharBlock(label='Text')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Obrázek'))]))], blank=True, null=True),
        ),
    ]
