# Generated by Django 3.0.7 on 2021-02-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0011_auto_20210206_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='banner_cta',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='banner_subtitle',
        ),
    ]
